#!/usr/bin/env python3
"""Run prompt-adherence demos against Databricks FMAPI + MCP tool functions.

Uses the same system prompt and tool implementations as the deployed MCP server.
Produces docs/demos/agent_transcripts.json and docs/demos/AGENT_TRANSCRIPTS.md.

Requires:
  DATABRICKS_HOST, DATABRICKS_TOKEN
  pip install openai 'databricks-sdk[openai]'
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "mcp_server"))

import weather_mcp_server as tools  # noqa: E402
from databricks.sdk import WorkspaceClient  # noqa: E402

SYSTEM = (ROOT / "agent" / "SYSTEM_PROMPT.md").read_text()
MODEL = os.environ.get("DEMO_MODEL", "databricks-meta-llama-3-3-70b-instruct")

OPENAI_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "Get current temperature, conditions, humidity, and wind.",
            "parameters": {
                "type": "object",
                "properties": {"location": {"type": "string"}},
                "required": ["location"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_forecast",
            "description": "Get a multi-day daily forecast.",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {"type": "string"},
                    "days": {"type": "integer"},
                },
                "required": ["location"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_travel_recommendation",
            "description": "Umbrella/jacket recommendation from forecast thresholds.",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {"type": "string"},
                    "date": {"type": "string"},
                },
                "required": ["location"],
            },
        },
    },
]

DISPATCH = {
    "get_current_weather": lambda **kw: tools.get_current_weather(kw["location"]),
    "get_forecast": lambda **kw: tools.get_forecast(
        kw["location"], int(kw.get("days", 5))
    ),
    "get_travel_recommendation": lambda **kw: tools.get_travel_recommendation(
        kw["location"], kw.get("date") or ""
    ),
}


def run_agent(question: str) -> list[dict]:
    w = WorkspaceClient(
        host=os.environ["DATABRICKS_HOST"], token=os.environ["DATABRICKS_TOKEN"]
    )
    client = w.serving_endpoints.get_open_ai_client()
    messages = [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": question},
    ]
    transcript: list[dict] = [{"role": "user", "content": question}]
    for _ in range(5):
        resp = client.chat.completions.create(
            model=MODEL,
            messages=messages,
            tools=OPENAI_TOOLS,
            temperature=0.1,
        )
        msg = resp.choices[0].message
        tool_calls = getattr(msg, "tool_calls", None) or []
        if not tool_calls:
            transcript.append({"role": "assistant", "content": msg.content or ""})
            return transcript
        messages.append(
            {
                "role": "assistant",
                "content": msg.content or "",
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.function.name,
                            "arguments": tc.function.arguments,
                        },
                    }
                    for tc in tool_calls
                ],
            }
        )
        for tc in tool_calls:
            name = tc.function.name
            args = json.loads(tc.function.arguments or "{}")
            result = DISPATCH[name](**args)
            transcript.append(
                {
                    "role": "tool_call",
                    "tool": name,
                    "arguments": args,
                    "result": result,
                }
            )
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "content": json.dumps(result),
                }
            )
    transcript.append({"role": "assistant", "content": "(max steps reached)"})
    return transcript


def to_markdown(all_out: list[dict]) -> str:
    lines = [
        "# Agent transcripts (prompt adherence demos)",
        "",
        "Generated by `scripts/run_agent_demos.py` using:",
        f"- Model: `{MODEL}` (Databricks Model Serving)",
        "- System prompt: `agent/SYSTEM_PROMPT.md`",
        "- Tools: same functions exposed by the deployed MCP server",
        "  (`mcp_server/weather_mcp_server.py` → Open-Meteo broker)",
        "",
        "> These transcripts prove the **prompt + tools** behavior end-to-end.",
        "> For full Agent Bricks UI credit, also attach screenshots of the",
        "> Agent Bricks config (MCP attached) from the workspace UI.",
        "",
    ]
    for i, item in enumerate(all_out, 1):
        lines.append(f"## {i}. {item['question']}")
        lines.append("")
        for turn in item["transcript"]:
            if turn["role"] == "user":
                lines.append(f"**User:** {turn['content']}")
            elif turn["role"] == "tool_call":
                lines.append("")
                lines.append(
                    f"**Tool call:** `{turn['tool']}({json.dumps(turn['arguments'])})`"
                )
                lines.append("")
                lines.append("```json")
                lines.append(json.dumps(turn["result"], indent=2)[:2000])
                lines.append("```")
            elif turn["role"] == "assistant":
                lines.append("")
                lines.append(f"**Assistant:** {turn['content']}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not os.environ.get("DATABRICKS_HOST") or not os.environ.get("DATABRICKS_TOKEN"):
        print("Set DATABRICKS_HOST and DATABRICKS_TOKEN", file=sys.stderr)
        return 1
    questions = [
        "What's the weather in Chicago right now?",
        "Should I bring a jacket and umbrella to Seattle tomorrow?",
        "What's the weather in Nowhereville, Atlantis?",
    ]
    all_out = []
    for q in questions:
        print("Running:", q)
        transcript = run_agent(q)
        all_out.append(
            {
                "question": q,
                "transcript": transcript,
                "model": MODEL,
                "system_prompt_source": "agent/SYSTEM_PROMPT.md",
                "tools_backend": "mcp_server weather tools (same as deployed MCP)",
            }
        )
    out_dir = ROOT / "docs" / "demos"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "agent_transcripts.json").write_text(json.dumps(all_out, indent=2))
    (out_dir / "AGENT_TRANSCRIPTS.md").write_text(to_markdown(all_out))
    print("Wrote", out_dir / "agent_transcripts.json")
    print("Wrote", out_dir / "AGENT_TRANSCRIPTS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
